# DataBase Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/mdzMueblesbd
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=create-drop
spring.servlet.multipart.max-file-size=10MB
# Tamaño máximo total de la petición (por ejemplo, 50MB)
spring.servlet.multipart.max-request-size=50MB

# Logging Configuration - Solo mostrar logs de tu aplicación
logging.level.root=ERROR
logging.level.org.springframework=ERROR
logging.level.org.hibernate=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.apache=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.springframework.security=ERROR
logging.level.org.springframework.boot=ERROR

# Mantener solo los logs de tu aplicación para ver lo que va ejecutando
logging.level.com.Capinteria.carpinteria=INFO

# Configurar el patrón del log más limpio - solo hora, nivel y mensaje
logging.pattern.console=%clr(%d{HH:mm:ss}){blue} %clr(%5p){green} %clr(:){faint} %m%n

# Deshabilitar banner de Spring Boot
spring.main.banner-mode=off
